sbx_metallophore_rescue:
  antismash:
    db: /work/dsamuelson/databases/antismash_db
  references:
    refseq: /work/dsamuelson/databases/refseq_complete.fna
    gtdb: /work/dsamuelson/databases/gtdb_reps.fna
  thresholds:
    min_align_frac: 0.5
  fegenie:
    discovery_stringency: low
    confirm_stringency: medium
