<<<<<<< HEAD
sbx_metallophore_rescue:
  example_rule_options: /path/to/example_rule_thingy
=======
# List of sample IDs (these should match the names Sunbeam uses for assemblies)
samples:
  - sample1
  - sample2

# Reference databases
references:
  agora: /path/to/agora2/blastdb/agora2
  ncbi: /path/to/ncbi/refseq/blastdb/refseq
  mibig: /path/to/mibig/blastdb/mibig

>>>>>>> 62d09d9 (commit)
