sbx_metallophore_rescue:
  antismash:
    db: /work/dsamuelson/mmandolfo/metallophore_sunbeam_extension_test/test_ref.mmi
  references:
    refseq: /work/dsamuelson/mmandolfo/metallophore_sunbeam_extension_test/test_ref.mmi
    gtdb: /work/dsamuelson/mmandolfo/metallophore_sunbeam_extension_test/test_ref.mmi
  thresholds:
    min_align_frac: 0.5
  fegenie:
    discovery_stringency: low
    confirm_stringency: medium
